config/routes.rb
Rails.application.routes.draw do
  
  root to: 'posts#index'

  get '/login' => 'admin/sessions#new'
  get '/logout' => 'admin/sessions#destroy'

  namespace :admin do
    resources :posts
    resources :settings, only: [:new, :create, :edit, :update]
    resources :dashboard, only: [:index]
    resources :notifications, only: [:index, :destroy]
    resources :messages, only: [:index, :show, :update, :destroy]
    resources :visitors, only: [:index, :destroy]
    resources :comments, only: [:index, :update, :destroy]
    resources :tags, except: [:index]
    resources :sessions, only: [:new, :create, :destroy]
    resources :moderators, only: [:index, :edit, :update]
  end

  resources :posts, only: [:index, :show]
  resources :messages, only: [:new, :create]
  resources :comments, only: [:create]

  match 'dismiss_all_notifications', to: 'admin/notifications#delete_all', via: :delete
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  message    :text
#  status     :boolean
#  post_id    :integer
#  visitor_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :visitor
  has_many  :notifications, as: :notifiable, dependent: :destroy

  validates	:message, presence: true

  scope :approved, -> { where status: true }

  def self.matching_fullname_or_message params
    joins(:visitor).where("fullname LIKE ? OR message LIKE ?", "%#{params}%", "%#{params}%")
  end

  include Notifiable
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::ApplicationController
  def index
    if params[:search].present?
      @comments = Comment.matching_fullname_or_message(params[:search]).page params[:page]
    else
      @comments = Comment.where(status: to_bool(params[:status])).page params[:page]
    end
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(status: params[:status])
      redirect_to :back, notice: 'Successfully updated comment'
    else
      redirect_to :back, notice: 'There was a problem updating comment'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    redirect_to :back, notice: 'Successfully deleted comment'
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  	if visitor.save
  		flash[:notice] = "Successfully created new comment"
  	else
  		flash[:alert] = "There was a problem creating your comment"
  		set_visitor_sessions
  	end

  	redirect_to :back
  end

  private

  def visitor_comments_params
  	params.require(:visitor).permit(:fullname, :email, :comments_attributes => [:message, :post_id])
  end

  def visitor
  	@visitor ||= VisitorCommentService.new(visitor_comments_params).visitor
  end

  def set_visitor_sessions
  	session[:visitor_errors] = visitor.errors.full_messages
  	session[:visitor_params] = visitor_comments_params
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/admin/comments/index.html.erb
<h1>Comments</h1>

<p><%= render 'search', route: admin_comments_path %></p>

<p>
  <%= link_to 'Approved', admin_comments_path(status: true) %>
  <%= link_to 'Un-approved', admin_comments_path(status: false) %>
</p>

<% @comments.each do |comment| %>
  <p><b><%= comment.visitor.fullname %></b> posted message on <b><%= comment.post.title %></b></p>
  <p><%= comment.message %></p>
  <p>
    <%= link_to 'Delete', admin_comment_path(comment), method: :delete, data: {confirm: 'Are you sure?'} %>
    <%=
      if params[:status] == 'true'
        link_to 'Un-approved', admin_comment_path(comment, status: false), method: :put
      else
        link_to 'Aapproved', admin_comment_path(comment, status: true), method: :put
      end
    %> 
  </p>
  <hr>
<% end %>

<p><%= paginate @comments %></p>