config/routes.rb
Rails.application.routes.draw do
  
  root to: 'posts#index'

  get '/login' => 'admin/sessions#new'
  get '/logout' => 'admin/sessions#destroy'

  namespace :admin do
    resources :posts
    resources :settings, only: [:new, :create, :edit, :update]
    resources :dashboard, only: [:index]
    resources :notifications, only: [:index, :destroy]
    resources :messages, only: [:index, :show, :update, :destroy]
    resources :visitors, only: [:index, :destroy]
    resources :comments, only: [:index, :update, :destroy]
    resources :tags, except: [:index]
    resources :sessions, only: [:new, :create, :destroy]
    resources :moderators, only: [:index, :edit, :update]
  end

  resources :posts, only: [:index, :show]
  resources :messages, only: [:new, :create]
  resources :comments, only: [:create]

  match 'dismiss_all_notifications', to: 'admin/notifications#delete_all', via: :delete
end

app/models/notification.rb
# == Schema Information
#
# Table name: notifications
#
#  id              :integer          not null, primary key
#  notifiable_id   :integer
#  notifiable_type :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Notification < ActiveRecord::Base
  belongs_to :notifiable, polymorphic: true
end

app/controllers/admin/notifications_controller.rb
class Admin::NotificationsController < Admin::ApplicationController
  def index
    @visitor_notifications = Notification.where(notifiable_type: 'Visitor').order(id: :desc)
    @comment_notifications = Notification.where(notifiable_type: 'Comment').order(id: :desc)
  end

  def destroy
    @notifiable = Notification.find(params[:id])
    @notifiable.destroy

    redirect_to :back, notice: 'Notification was deleted successfully'
  end

  def delete_all
    Notification.delete_all
    redirect_to :back, notice: 'All notifications deleted successfully'
  end
end

app/helpers/admin/notifications_helper.rb
module Admin::NotificationsHelper
end

app/views/admin/notifications/index.html.erb
<h1>Notifications</h1>

<%=
  if Notification.any?
    link_to 'Dismiss All', dismiss_all_notifications_path, method: :delete, data: {confirm: 'Are you sure?'}
  end
%>

<% @visitor_notifications.each do |notif| %>
  <p>
    <%= "#{notif.notifiable.fullname} added as a new visitor #{time_ago notif.created_at}" %>
    <%= link_to 'Dismiss', admin_notification_path(notif), method: :delete, data: {confirm: 'Are you sure?'} %>
  </p>
<% end %>

<hr>

<% @comment_notifications.each do |notif| %>
  <p>
    <%#= "#{notif.notifiable.message} was added #{time_ago notif.created_at}" %>
    <%= "#{notif.notifiable.visitor.fullname} added a comment #{time_ago notif.created_at}" %>
    <%= link_to 'Dismiss', admin_notification_path(notif), method: :delete, data: {confirm: 'Are you sure?'} %>
  </p>
<% end %>